{{- if .Values.controller.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "jenkins.label" .}}"
    {{- end }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "{{ .Release.Name }}-{{ .Values.controller.componentName }}"
{{- if .Values.controller.route.labels }}
{{ toYaml .Values.controller.route.labels | indent 4 }}
{{- end }}
{{- if .Values.controller.route.annotations }}
  annotations:
{{ toYaml .Values.controller.route.annotations | indent 4 }}
{{- end }}
  name: {{ template "jenkins.fullname" . }}
spec:
  host: {{ .Values.controller.route.path }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIGozCCBYugAwIBAgIIWtdCeEPGzx0wDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
      BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
      GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
      LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
      cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMjMxMDE5MTIzODMwWhcN
      MjQxMTE5MTIzODMwWjAgMR4wHAYDVQQDDBUqLnNtYXJ0c3RyZWFtLW9rZC5jb20w
      ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDcPYYObIZVqOHRLdFGbohe
      lZVDgFlejukKxbvQZDhb17S8tlSnFnvCVwGZglCp6CBlb/wJCY9x8Wqyg5bljJqJ
      LE15ti+QM06gxtpqxiSSB9g0SCKpugPoeykPX1KDT+uwhjw6ykQRHbKLigYQsLB7
      axwVQBM2JDk4YfGwDzjK92Yok5zHYdgc2ARjGFf5gRq+6lA5uy66r7fnJy8c3U6+
      r+dH5KYhFNWbjVW4lx6q//6MUorZm9BvsirViSrhRsosZiaDUCZ0+DcpyCQfiXcO
      3jH4OeE7HDg2W0D7ig/WwwziIAiu1C067KY5ZiChJyWj9y0Yj8tlH6EAkKXYdm0b
      AgMBAAGjggNKMIIDRjAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
      BggrBgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwOQYDVR0fBDIwMDAuoCygKoYoaHR0
      cDovL2NybC5nb2RhZGR5LmNvbS9nZGlnMnMxLTEwMzQ2LmNybDBdBgNVHSAEVjBU
      MEgGC2CGSAGG/W0BBxcBMDkwNwYIKwYBBQUHAgEWK2h0dHA6Ly9jZXJ0aWZpY2F0
      ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS8wCAYGZ4EMAQIBMHYGCCsGAQUFBwEB
      BGowaDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMEAGCCsG
      AQUFBzAChjRodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRv
      cnkvZ2RpZzIuY3J0MB8GA1UdIwQYMBaAFEDCvSeOzDSDMKIz1/tss/C0LIDOMDUG
      A1UdEQQuMCyCFSouc21hcnRzdHJlYW0tb2tkLmNvbYITc21hcnRzdHJlYW0tb2tk
      LmNvbTAdBgNVHQ4EFgQUpLA/1c0UMsPsWK2RTOKrKEQY88cwggF8BgorBgEEAdZ5
      AgQCBIIBbASCAWgBZgB2AO7N0GTV2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7Wb
      AAABi0fxzGEAAAQDAEcwRQIgGqrRqCKu+oa5VDIfR/oZRUuEh+6BGA0Lstn9Diwh
      dyACIQDzKNodyQ4SHptIlRlw/XLg7mHowEB8BQ3qVEYDqV1UygB1AEiw42vapkc0
      D+VqAvqdMOscUgHLVt0sgdm7v6s52IRzAAABi0fxzR0AAAQDAEYwRAIgR0MFNB9I
      1oLS5xUzjAQsPgAAknkf2PPD7qTfpQQR5Y0CIG1lRe2rZB6xfIvcmbGtKdYOhaE/
      zcfxlWBuVVP/xoyRAHUA2ra/az+1tiKfm8K7XGvocJFxbLtRhIU0vaQ9MEjX+6sA
      AAGLR/HNzgAABAMARjBEAiBz5zvmba06DSGeFVmjVDCOONwxM3JZctz3GnfiyiW2
      0AIgBD3zYBmdNQxDzoUZsx1TasLPJhos/lL33YRyRabAMJswDQYJKoZIhvcNAQEL
      BQADggEBAJBRcLIudGtAkLKpq3I2KRYXevwixJ0SCTH5tEFyHOSt+9MOK2Q4IYbF
      bjeHXgTvyeXqpPZd7xxdrRii0fseEnBFfn2hchcn98yW/5RuVqyH92zL0Y3kSs2p
      9jojNq/tdIcjtpRPvhnNaXt4kOPSX5qFrqfaUJ3Tm48p8zKrEgP2St3/AqqbeqCT
      028/GB3RrJ3MQQZjQG48zGHD81aUmzmLNxKHK2M2+1sHVXmevn+nv6Vy2M3Eu96f
      QT21DFkA3N7z4WTNgkCXOCedklhgcqAEgefk8ayrI1/a0uxIO269rApzCaf2gFpP
      smrtquP8PijoNS//Y75s29KU4EpgkUw=
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcPYYObIZVqOHR
      LdFGbohelZVDgFlejukKxbvQZDhb17S8tlSnFnvCVwGZglCp6CBlb/wJCY9x8Wqy
      g5bljJqJLE15ti+QM06gxtpqxiSSB9g0SCKpugPoeykPX1KDT+uwhjw6ykQRHbKL
      igYQsLB7axwVQBM2JDk4YfGwDzjK92Yok5zHYdgc2ARjGFf5gRq+6lA5uy66r7fn
      Jy8c3U6+r+dH5KYhFNWbjVW4lx6q//6MUorZm9BvsirViSrhRsosZiaDUCZ0+Dcp
      yCQfiXcO3jH4OeE7HDg2W0D7ig/WwwziIAiu1C067KY5ZiChJyWj9y0Yj8tlH6EA
      kKXYdm0bAgMBAAECggEAHriU7trOhjuvfCk4TEB2Kei9pb5344vAZW3y5n0EVjNU
      P7qYkPy+41CVpYnFoghXdIQsE5VPerpigrzTm04t7ufMytHR9/sK2GcZ59OfHaDr
      Kf0h8KuaM0nyuUqM9595+z6jlM51Xi8r95uXgFPVL5y05yCaosO8w5OjTfFhn6tO
      kw7UYRfmieciQycm4vVQKmmrOSU6tlIIfmseaNmjX8pqUTC/zLunth8+SX91Gk9x
      3BOfWHFG1sRHNKDscLR0158sARkvynYCA/5Qr7ldx1y67pAkSdTxJNSF+qcPfgnK
      edLyHZgARkTmy0dxH/UvuwimyhvPyFE4Jg2/+NN/yQKBgQD2Jm2zBt737CSIBA6r
      LsnCXWSl0xsH+wMHfa6ah+nmUQV9pXA0GtyMBz8K+QT/kK9uUtgDHQVagcOdn3BU
      POEDMZXsZN7lanQG1V8tqjNegK5Ra4CL30Ta4grbQ0xUeIpwoff3bxl1Yjz7yyiX
      fCVEn7Wpc0uW2fiFFL51dZMm9QKBgQDlDayd94o2svInQpfZLxNe/1r1/0xSX1I2
      62Zt9NMapnaE0+0V3DE8mehnPDtD7yCISO63AUgsWnFUVEWiDWoEvCQNauMSxS9a
      NrxNHB/irLclK0myRo1S1/y37JQvN2QMXCheJog7NDdB9Atl26z9byT7xO5ZX8QH
      SL/TxXwZzwKBgQDjNYmg7UC3PIRkAMrBfIjEHo0e/ARBk5OyQHMBNV/UNwmId0Ng
      9UKLBs1MhZv1g0pL3bCC/zDH4Gv+fQOk3iUdW5H2CQ4uWdsLy7z1W9va6ZD+muqn
      McpO+MPorPAyMKopWXiYLzciwTFlgpvPaMrF015OMZyefEkIHqPHrGXOWQKBgQDf
      o75Kbgrw5T8xvf9s+l27fy9cyGvIcXFgVe6opUYI20cU4aa2lUstlEgpo9FpvuzQ
      pAUPgZzqUVQdtjpWwyokfV3mC9qx1P0q5A5ua2tmcqRPEjjea6xImsIRAlic0URK
      HSD87DpPM+hP6OvIA/ifagl+GQVvFeXcBtfk+Qj2WQKBgHLHth3I+IGWfN3ruz0z
      VWJnUvZdui9XiVfI7fpaB0Be8S7TOgNB0fuzCZw54Me1EAUCpBhZb1wft5Jx4KA/
      FhuLGkXDmj0fNUCNeFFAmWIKJQKOCo4PBmGZZwpjQNdMqaa6a7jYn1rwgcQDvKFF
      UaNkhASIkqJpWlaGyPpwjhDF
      -----END PRIVATE KEY-----
    caCertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
      EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
      EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
      ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
      MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
      EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
      CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
      EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
      BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
      K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
      cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
      pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
      eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
      AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
      HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
      9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
      b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
      b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
      CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
      MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
      91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
      RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
      DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
      GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
      LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEfTCCA2WgAwIBAgIDG+cVMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNVBAYTAlVT
      MSEwHwYDVQQKExhUaGUgR28gRGFkZHkgR3JvdXAsIEluYy4xMTAvBgNVBAsTKEdv
      IERhZGR5IENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMTAx
      MDcwMDAwWhcNMzEwNTMwMDcwMDAwWjCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgT
      B0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHku
      Y29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1
      dGhvcml0eSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3Fi
      CPH6WTT3G8kYo/eASVjpIoMTpsUgQwE7hPHmhUmfJ+r2hBtOoLTbcJjHMgGxBT4H
      Tu70+k8vWTAi56sZVmvigAf88xZ1gDlRe+X5NbZ0TqmNghPktj+pA4P6or6KFWp/
      3gvDthkUBcrqw6gElDtGfDIN8wBmIsiNaW02jBEYt9OyHGC0OPoCjM7T3UYH3go+
      6118yHz7sCtTpJJiaVElBWEaRIGMLKlDliPfrDqBmg4pxRyp6V0etp6eMAo5zvGI
      gPtLXcwy7IViQyU0AlYnAZG0O3AqP26x6JyIAX2f1PnbU21gnb8s51iruF9G/M7E
      GwM8CetJMVxpRrPgRwIDAQABo4IBFzCCARMwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
      HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMB8GA1Ud
      IwQYMBaAFNLEsNKR1EwRcbNhyz2h/t2oatTjMDQGCCsGAQUFBwEBBCgwJjAkBggr
      BgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMDIGA1UdHwQrMCkwJ6Al
      oCOGIWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Ryb290LmNybDBGBgNVHSAEPzA9
      MDsGBFUdIAAwMzAxBggrBgEFBQcCARYlaHR0cHM6Ly9jZXJ0cy5nb2RhZGR5LmNv
      bS9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAWQtTvZKGEacke+1bMc8d
      H2xwxbhuvk679r6XUOEwf7ooXGKUwuN+M/f7QnaF25UcjCJYdQkMiGVnOQoWCcWg
      OJekxSOTP7QYpgEGRJHjp2kntFolfzq3Ms3dhP8qOCkzpN1nsoX+oYggHFCJyNwq
      9kIDN0zmiN/VryTyscPfzLXs4Jlet0lUIDyUGAzHHFIYSaRt4bNYC8nY7NmuHDKO
      KHAN4v6mF56ED71XcLNa6R+ghlO773z/aQvgSMO3kwvIClTErF0UZzdsyqUvMQg3
      qm5vjLyb4lddJIGvl5echK1srDdMZvNhkREg5L4wn3qkKQmw4TRfZHcYQFHfjDCm
      rw==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEADCCAuigAwIBAgIBADANBgkqhkiG9w0BAQUFADBjMQswCQYDVQQGEwJVUzEh
      MB8GA1UEChMYVGhlIEdvIERhZGR5IEdyb3VwLCBJbmMuMTEwLwYDVQQLEyhHbyBE
      YWRkeSBDbGFzcyAyIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTA0MDYyOTE3
      MDYyMFoXDTM0MDYyOTE3MDYyMFowYzELMAkGA1UEBhMCVVMxITAfBgNVBAoTGFRo
      ZSBHbyBEYWRkeSBHcm91cCwgSW5jLjExMC8GA1UECxMoR28gRGFkZHkgQ2xhc3Mg
      MiBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTCCASAwDQYJKoZIhvcNAQEBBQADggEN
      ADCCAQgCggEBAN6d1+pXGEmhW+vXX0iG6r7d/+TvZxz0ZWizV3GgXne77ZtJ6XCA
      PVYYYwhv2vLM0D9/AlQiVBDYsoHUwHU9S3/Hd8M+eKsaA7Ugay9qK7HFiH7Eux6w
      wdhFJ2+qN1j3hybX2C32qRe3H3I2TqYXP2WYktsqbl2i/ojgC95/5Y0V4evLOtXi
      EqITLdiOr18SPaAIBQi2XKVlOARFmR6jYGB0xUGlcmIbYsUfb18aQr4CUWWoriMY
      avx4A6lNf4DD+qta/KFApMoZFv6yyO9ecw3ud72a9nmYvLEHZ6IVDd2gWMZEewo+
      YihfukEHU1jPEX44dMX4/7VpkI+EdOqXG68CAQOjgcAwgb0wHQYDVR0OBBYEFNLE
      sNKR1EwRcbNhyz2h/t2oatTjMIGNBgNVHSMEgYUwgYKAFNLEsNKR1EwRcbNhyz2h
      /t2oatTjoWekZTBjMQswCQYDVQQGEwJVUzEhMB8GA1UEChMYVGhlIEdvIERhZGR5
      IEdyb3VwLCBJbmMuMTEwLwYDVQQLEyhHbyBEYWRkeSBDbGFzcyAyIENlcnRpZmlj
      YXRpb24gQXV0aG9yaXR5ggEAMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQAD
      ggEBADJL87LKPpH8EsahB4yOd6AzBhRckB4Y9wimPQoZ+YeAEW5p5JYXMP80kWNy
      OO7MHAGjHZQopDH2esRU1/blMVgDoszOYtuURXO1v0XJJLXVggKtI3lpjbi2Tc7P
      TMozI+gciKqdi0FuFskg5YmezTvacPd+mSYgFFQlq25zheabIZ0KbIIOqPjCDPoQ
      HmyW74cNxA9hi63ugyuV+I6ShHI56yDqg+2DzZduCLzrTia2cyvk0/ZM/iZx4mER
      dEr/VxqHD3VILs9RaRegAhJhldXRQLIQTO7ErBBDpqWeCtWVYpoNz4iCxTIM5Cuf
      ReYNnyicsbkqWletNw+vHX/bvZ8=
      -----END CERTIFICATE-----
  to:
    kind: Service
    name: {{ template "jenkins.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
