apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "file-secret-example-k8s"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "secretFile"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "secret file credential from Kubernetes"
type: Opaque
stringData:
  filename: mySecret.txt
data:
# base64 encoded bytes
  data: eyJhdXRocyI6eyJhdXJvcmFuZXh1cy5zbWFydHN0cmVhbS1zdHAuY29tOjUwMDAiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiJEdsb2JVc3JGb3IzJCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5vcmciLCJhdXRoIjoiWVdSdGFXNDZKRWRzYjJKVmMzSkdiM0l6SkE9PSJ9fX0= # Hello World!