apiVersion: v1
kind: Secret
metadata:
  name: "user-password-k8s"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: user
  password: 'passw0rd'