controller:
  JCasC:
    configScripts:
      clouds: |
        jenkins:
          clouds:
            - kubernetes:
                name: "okd"
                namespace: "qa-jenkins"
                jenkinsUrl: "http://qa-jenkins.qa-jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "qa-jenkins-agent.qa-jenkins.svc.cluster.local:50000"
                maxRequestsPerHostStr: "32"
                name: "kubernetes"
                namespace: "qa-jenkins"
                serverUrl: "https://kubernetes.default"
                podLabels:
                - key: "jenkins/default-agent"
                  value: "true"
                - key: "jenkins/docker-builder-agent"
                  value: "true"
                - key: "jenkins/python-agent"
                  value: "true"
                templates:

                  - name: "default"
                    namespace: "qa-jenkins"
                    containers:
                    - name: "jnlp"
                      alwaysPullImage: false
                      args: "^${computer.jnlpmac} ^${computer.name}"
                      command: 
                      envVars:
                        - envVar:
                            key: "JENKINS_URL"
                            value: "http://qa-jenkins.qa-jenkins.svc.cluster.local:8080/"
                        - envVar:
                            key: "DOCKER_REGISTRY"
                            value: "https://auroranexus.smartstream-stp.com:5000"
                      image: "jenkins/inbound-agent:3107.v665000b_51092-15"
                      privileged: "false"
                      resourceLimitCpu: 512m
                      resourceLimitMemory: 512Mi
                      resourceRequestCpu: 512m
                      resourceRequestMemory: 512Mi
                      runAsUser: 
                      runAsGroup: 
                      ttyEnabled: false
                      workingDir: /home/jenkins/agent
                    idleMinutes: 0
                    instanceCap: 2147483647
                    label: "default-agent"
                    nodeUsageMode: "NORMAL"
                    podRetention: Never
                    showRawYaml: false
                    serviceAccount: "qa-jenkins"
                    slaveConnectTimeoutStr: "100"
                    yamlMergeStrategy: override

                  - name: python
                    label: "python-agent"
                    serviceAccount: "qa-jenkins"
                    showRawYaml: false
                    containers:
                    - name: python
                      image: python:3
                      command: "/bin/sh -c"
                      args: "cat"
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "400m"
                      resourceRequestMemory: "512Mi"
                      resourceLimitCpu: "1"
                      resourceLimitMemory: "1024Mi"
                      runAsUser: 1000
                      runAsGroup: 1000
                  
                  - name: maven
                    label: "maven-agent"
                    showRawYaml: false
                    volumes:
                    - persistentVolumeClaim:
                        mountPath: '/home/jenkins/agent/.m2/repository'
                        claimName: maven-repo-pvc
                        readOnly: false
                    containers:
                    - name: maven
                      image: maven:3
                      command: "sleep"
                      args: "99d"
                      envVars:
                        - envVar:
                            key: "HOME"
                            value: "/home/jenkins/agent/"
                        - envVar:
                            key: "MAVEN_CONFIG"
                            value: "/home/jenkins/agent/.m2/"
                        - secretEnvVar:
                            key: "NEXUS_USERNAME"
                            secretName: "nexus-reg-admin-user-k8s"
                            secretKey: "username"  
                        - secretEnvVar:
                            key: "NEXUS_PASSWORD"
                            secretName: "nexus-reg-admin-user-k8s"
                            secretKey: "password"
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "400m"
                      resourceRequestMemory: "512Mi"
                      resourceLimitCpu: "1"
                      resourceLimitMemory: "1024Mi"
                      runAsUser: 1000
                      runAsGroup: 1000
                    yamlMergeStrategy: "merge"
                    yaml: |
                      kind: Pod
                      metadata:
                        name: maven
                      spec:
                        containers:
                        - name: maven
                          volumeMounts:
                            - name: mvn-settings
                              mountPath: "/home/jenkins/agent/.m2/"
                        volumes:
                        - name: mvn-settings
                          secret:
                              secretName: mvn-settings-secret-k8s
                              items:
                                - key: maven-settings.xml
                                  path: settings.xml

                  - name: newman
                    label: "newman-agent"
                    showRawYaml: false
                    containers:
                    - name: newman
                      image: pstauffer/newman-htmlextra
                      command: "sleep"
                      args: "99d"
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "200m"
                      resourceRequestMemory: "256Mi"
                      resourceLimitCpu: "400m"
                      resourceLimitMemory: "256Mi"
                      runAsUser: 1000
                      runAsGroup: 1000     

                  - name: awsCli
                    label: "aws-cli"
                    showRawYaml: false
                    containers:
                    - name: aws-cli
                      image: auroraharbor.smartstream-stp.com/devops/aws-cli:1.0
                      command: "sleep"
                      args: "300000"
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "200m"
                      resourceRequestMemory: "256Mi"
                      resourceLimitCpu: "400m"
                      resourceLimitMemory: "256Mi"
                      runAsUser: 1000
                      runAsGroup: 1000

                  - name: cloudStorageService
                    label: "cloud-storage-service-agent"
                    showRawYaml: false
                    containers:
                    - name: cloud-storage-service
                      image: auroranexus.smartstream-stp.com:5000/pegasus-cloud-storage-service:0.1.0-SNAPSHOT
                      envVars:
                        - envVar:
                            key: "AWS_URL"
                            value: ""
                        - envVar:
                            key: "AWS_REGION"
                            value: ""
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "200m"
                      resourceRequestMemory: "256Mi"
                      resourceLimitCpu: "400m"
                      resourceLimitMemory: "256Mi"
                      runAsUser: 1000
                      runAsGroup: 1000 
                  
                  - name: cosign
                    label: "signing-agent"
                    showRawYaml: false
                    containers:
                    - name: cosign
                      image: auroranexus.smartstream-stp.com:5000/cosign
                      command: "sleep"
                      args: "99d"
                      ttyEnabled: true
                      privileged: false
                      resourceRequestCpu: "200m"
                      resourceRequestMemory: "256Mi"
                      resourceLimitCpu: "200m"
                      resourceLimitMemory: "256Mi"
                      envVars:
                      - secretEnvVar:
                          key: "COSIGN_KEY"
                          secretName: "cosign-k8s"
                          secretKey: "COSIGN_KEY" 
                      - secretEnvVar:
                          key: "COSIGN_PUB"
                          secretName: "cosign-k8s"
                          secretKey: "COSIGN_PUB"                   
                      - secretEnvVar:
                          key: "OCI_REGISTRY"
                          secretName: "cosign-k8s"
                          secretKey: "OCI_REGISTRY"                   
                      - secretEnvVar:
                          key: "OCI_PASS"
                          secretName: "cosign-k8s"
                          secretKey: "OCI_PASS"
                      - secretEnvVar:
                          key: "OCI_LOGIN"
                          secretName: "cosign-k8s"
                          secretKey: "OCI_LOGIN"
                      - secretEnvVar:
                          key: "COSIGN_PASS"
                          secretName: "cosign-k8s"
                          secretKey: "COSIGN_PASS"   

                  - name: kaniko
                    showRawYaml: false
                    label: "docker-builder-agent"
                    serviceAccount: "qa-jenkins"
                    containers:
                    - name: kaniko
                      image: gcr.io/kaniko-project/executor:debug
                      command: "/busybox/cat"
                      ttyEnabled: true
                      runAsUser: 1000
                      runAsGroup: 1000
                    
                    ### alternative example how to mount volume from secret
                    # volumes:
                    # - secretVolume:
                    #     mountPath: "/kaniko/.docker"
                    #     optional: false
                    #     secretName: "nexus-reg-k8s"
                    
                    yamlMergeStrategy: "merge"
                    yaml: |
                      kind: Pod
                      metadata:
                        name: kaniko
                      spec:
                        containers:
                        - name: kaniko
                          volumeMounts:
                            - name: kaniko-secret
                              mountPath: /kaniko/.docker
                        volumes:
                        - name: kaniko-secret
                          secret:
                              secretName: nexus-reg-k8s
                              items:
                                - key: .dockerconfigjson
                                  path: config.json