controller:
  JCasC:
    configScripts:
      ldap: |
        jenkins:             
          securityRealm:
            ldap:
              configurations:
                - groupSearchBase: "dc=sst,dc=stp"
                  groupSearchFilter: "(&(objectclass=group)(cn={0}))"
                  inhibitInferRootDN: true
                  managerDN: "ldapjenkokd@sst.stp"
                  managerPasswordSecret: "{AQAAABAAAAAQsfTI0nIzIV/m9vuHzefpdpk87Of00nvdbh/zgehTHHg=}"
                  server: "192.168.111.2:3268"
                  userSearch: "sAMAccountName={0}"
                  userSearchBase: "dc=sst,dc=stp"
                - inhibitInferRootDN: false
                  managerDN: "cn=admin,dc=smartstream-okd,dc=com"
                  managerPasswordSecret: "{AQAAABAAAAAQPJZ52HlUB6bJ+2oOuhaSTZyGeyXvqjhNuhXrGwRF6tY=}"
                  rootDN: "dc=smartstream-okd,dc=com"
                  server: "192.168.62.155:389"
              disableMailAddressResolver: false
              disableRolePrefixing: true
              groupIdStrategy: "caseInsensitive"
              userIdStrategy: "caseInsensitive"

          authorizationStrategy:
            globalMatrix:
              entries:
              - group:
                  name: "authenticated"
                  permissions:
                  - "Agent/Build"
                  - "Job/Build"
                  - "Job/Read"
                  - "Overall/Read"
                  - "View/Read"
              - user:
                  name: "MilijicB"
                  permissions:
                  - "Overall/Administer"
              - user:
                  name: "ShevchenkoV"
                  permissions:
                  - "Overall/Administer"
              - user:
                  name: "ZaborovD"
                  permissions:
                  - "Overall/Administer"
              - user:
                  name: "aalekseev"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Replay"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
              - user:
                  name: "abondar"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
              - user:
                  name: "dkarpesh"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Connect"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Discover"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
              - user:
                  name: "olivap"
                  permissions:
                  - "Credentials/View"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Read"
                  - "Overall/Read"
              - user:
                  name: "parak"
                  permissions:
                  - "Overall/Administer"
              - user:
                  name: "phholmatov"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Connect"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
              - user:
                  name: "sandner"
                  permissions:
                  - "Overall/Administer"
              - user:
                  name: "testuser"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
              - user:
                  name: "vardelyanov"
                  permissions:
                  - "Agent/Build"
                  - "Agent/Configure"
                  - "Agent/Create"
                  - "Agent/Delete"
                  - "Agent/Disconnect"
                  - "Job/Build"
                  - "Job/Cancel"
                  - "Job/Configure"
                  - "Job/Create"
                  - "Job/Delete"
                  - "Job/Move"
                  - "Job/Read"
                  - "Job/Workspace"
                  - "Metrics/HealthCheck"
                  - "Metrics/ThreadDump"
                  - "Metrics/View"
                  - "Overall/Read"
                  - "Run/Delete"
                  - "Run/Update"
                  - "SCM/Tag"
                  - "View/Configure"
                  - "View/Create"
                  - "View/Delete"
                  - "View/Read"
